### PR TITLE
sovok.tv fixes

### PR DESCRIPTION
**Pull request by ancwrd1**
- Fix for the new API used since 25-02-2013
- Added streamer setting UI
- Generic license fix for bitbake build

### CODE REVIEW

**Comment by technic** [comment]
Wy change kartina api ?

**Comment by ancwrd1** [comment]
Cuz it is a base class for sovok.tv API and it's functions are inherited.

**Comment by zakalibit** [comment]
Hi dremon,
I did not look in detail, but my concern is if the other plugins are not affected bu this change.

**Comment by ancwrd1** [comment]
It's a very minor change; I believe it should not have any impact on existing plugins.
Basically it does just this: instead of "/api/xml/..." the self.apipath+"/xml/..." construct is used.
self.apipath is "/api" by default and for sovok.tv it is "/v2.0".

**Comment by zakalibit** [comment]
sounds reasonable, still need to see technic's final opinion, as he is the solution architect :))))))

**Comment by technic** [comment]
It is ok

**Pull request merged**
